services:

  backend:

    build:
      context: ./backend

    container_name: aerovision_backend

    ports:
      - "8000:8000"

    volumes:
      - ./datasets:/datasets
      - ./data-warehouse:/app/data-warehouse

  frontend:

    build:
      context: ./frontend

    container_name: aerovision_frontend

    ports:
      - "8080:8080"

    depends_on:
      - backend